### ISSUE TITLE
Missing boundary annotation for parameters like "number of x"

### ISSUE THREAD

**Issue by GideonKoenig** [Safe-DS/Library-Analyzer#41]
### URL Hash

#/sklearn/sklearn.ensemble._forest/RandomForestClassifier/__init__/n_estimators

### Expected Annotation Type

`@boundary`

### Expected Annotation Inputs

Discret: 0 <= x 

### Suggested Solution (optional)

Entweder an SciKit weiterleiten, oder vielleicht irgendwie ueber das "number of" automatisiert erkennen.

**Comment by nvollroth** [comment]
This boundary would be built on assumptions that we would analyze here. However, that is not planned here.
