### ISSUE TITLE
Function to resolve references

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Library-Analyzer#90]
### Is your feature request related to a problem?

As a basis for the data flow analysis we need to know the declaration(s) that a reference can point to.

### Desired solution

A function `resolve_reference` that takes an `astroid.Name` node (or another node that represents a reference) and returns a list of the possible

* parameters
* local variables
* global variables
* class attributes
* instance attributes

that the reference can point to.

If we cannot list all candidates, this should be clearly indicated. Since this function is the basis for any further analysis, it should be well tested.

**Comment by lukarade** [comment]
This issue is still in progress, so it should not be closed yet.
